#!/usr/bin/env node

const path = require('path')
const exec = require('./exec')
const pjson = require(path.join(process.cwd(), 'package.json'))
const version = process.argv[2]

function prepublish() {
  if (!pjson.scripts.prepublishOnly) return
  process.env.ANYCLI_NEXT_VERSION = version
  exec('yarn', ['run', 'prepublishOnly'])
}

prepublish()
