#!/usr/bin/env node

const path = require('path')
const exec = require('./exec')
const pjson = require(path.join(process.cwd(), 'package.json'))

function prepublish() {
  if (!pjson.scripts.prepublishOnly) return
  exec('yarn', ['run', 'prepublishOnly'])
}

prepublish()
