#!/usr/bin/env node

const path = require('path')
const pjson = require(path.join(process.cwd(), 'package.json'))
const exec = require('./exec')

pjson.scripts = pjson.scripts || {}

if (pjson.scripts.postpublish) {
  exec('yarn', ['run', 'postpublish'])
}
