#!/usr/bin/env node

const path = require('path')
const version = process.argv[2]
const pjson = require(path.join(process.cwd(), 'package.json'))
const exec = require('./exec')

function typedoc() {
  if (!pjson.devDependencies.typedoc) return
  exec.shell('git clone -b gh-pages $CIRCLE_REPOSITORY_URL gh-pages')
  exec.shell('typedoc --out /tmp/docs src/index.ts --excludeNotExported --mode file')
  exec.shell('rm -rf ./gh-pages/*')
  exec.shell('mv /tmp/docs/* ./gh-pages')
  process.chdir('gh-pages')
  exec.shell('git add -A')
  exec.shell(`git commit -m "updates from ${version} [skip ci]"`)
  exec.shell('git push')
}

typedoc()
